### PR TITLE
KeyError: 'url' during layer upload to GeoNode

### PR DESCRIPTION
**Pull request by Gpetrak**
This PR solves the `keyError: 'url'` which reported in the following [issue](https://github.com/GeoNode/QGISGeoNodePlugin/issues/263).

### CODE REVIEW

**Review by giohappy — CHANGES_REQUESTED** [review]
@Gpetrak only include the fix to "url" and move the formatting to a dedicated PR, otherwise it's not clear what is related to the issue and what just reformatting.

**Comment by Gpetrak** [comment]
@giohappy , you 're right. Done

**Review by giohappy — APPROVED** [review]

**Comment by smallvalthoss** [comment]
If we want the latest changes, like this one, how do we get them?

**Comment by smallvalthoss** [comment]
@giohappy awesome thank you!

**Pull request merged**
